### PR TITLE
Added initial support for osfamily RedHat.

### PR DESCRIPTION
**Pull request by dforsberg**
Hi,

I have added initial support for osfamily RedHat. It is tested on CentOS/RHEL6 

CentOS/RHEL7 uses systemd so it probably will conflict right now.

TODO:
Add systemd support.

### CODE REVIEW

**Comment by dforsberg** [comment]
I'm no god at writing spec tests...
any suggestions?

**Comment by dforsberg** [comment]
Now tests for Debian works again at least, :-)

**Comment by dforsberg** [comment]
Tests added for osfamily RedHat :-)

**Comment by aerostitch** [comment]
Hi @dforsberg ,

Sorry for the late reply, I was out.
I'll check that today. Thanks a lot for this addition! :)

Joseph

**Comment by aerostitch** [comment]
Well, that sounds like perfect. Thanks for the contribution! 👍

**Comment by aerostitch** [comment]
Just one question: Which versions of RedHat did you test it with? (Just to add in the metadata.json)

**Comment by dforsberg** [comment]
I have tested on CentOS and RHEL 6 
CentOS/RHEL7 will probably not work in this state due to systemd is used in the maxscale rpm.

**Comment by aerostitch** [comment]
Ok, thanks. That's a good start! :)
I'll add this to the metadata.json.

**Comment by aerostitch** [comment]
Change released as part of 1.1.0

**Pull request merged**
